<?php

namespace J\Tests\Fixtures;

/**
 * Class MockContainer
 *
 * @package J\Tests\Fixtures
 */
class MockContainer extends \Pimple\Container {


	public function offsetSet($id, $value) {
		parent::offsetSet($id, $value); // TODO: Change the autogenerated stub
	}

	public function offsetGet($id) {
		return parent::offsetGet($id); // TODO: Change the autogenerated stub
	}

	public function offsetExists($id) {
		return parent::offsetExists($id); // TODO: Change the autogenerated stub
	}
}
